BI-2451 - Setup jdbc evergreen project

diff --git a/.evg.yml b/.evg.yml
--- a/.evg.yml
+++ b/.evg.yml
@@ -6,8 +6,13 @@ pre:
   - func: "export variables"
 
 post:
-  - func: "upload test results"
   - func: "upload jar file"
+  - func: "upload test classes"
+  - func: "upload test packages"
+  - func: "upload test js"
+  - func: "upload test css"
+  - func: "upload test index"
+  - func: "upload xunit test results"
 
 buildvariants:
   - name: ubuntu1804-64-jdk-8
@@ -35,6 +40,7 @@ functions:
     command: shell.exec
     type: test
     params:
+      working_dir: adl-jdbc-driver
       script: |
           ${PREPARE_SHELL}
           # this also runs the unit tests.
@@ -43,39 +49,58 @@ functions:
   "export variables":
     - command: shell.exec
       params:
-        silent: true
         working_dir: adl-jdbc-driver
         script: |
 
-          export PLATFORM='${_platform|unset}'
-          . "./build_scripts/prepare-shell.sh"
+          # set the state needed irrespective of _platform
+          ARTIFACTS_DIR=artifacts
+          S3_ARTIFACTS_DIR='adl-sql-driver/artifacts/${version_id}/${build_variant}'
+          S3_RELEASES_DIR='adl-sql-driver/releases/${version_id}/${build_variant}'
 
-          export S3_ARTIFACTS_DIR='adl-jdbc-driver/artifacts/${version_id}'
-          export S3_RELEASES_DIR='adl-jdbc-driver/releases/${version_id}'
+          # get the version from the gradle.properties file, so we don't need to update in two places.
+          MDBJDBC_VER="$(cat "gradle.properties" | head -n 1 | sed  s'/version\s*=\s*//')"
+
+          case '${_platform}' in
+          ubuntu1804-64-jdk-8)
+               JAVA_HOME=/opt/java/jdk8
+          ;;
+          ubuntu1804-64-jdk-11)
+               JAVA_HOME=/opt/java/jdk11
+          ;;
+          *)
+               echo "ERROR: invalid value for \${_platform}: '$_platform'"
+               echo "Allowed values: 'ubuntu1604-64-jdk-8', 'ubuntu1604-64-jdk-11'"
+               exit 1
+          ;;
+          esac
+
+          # export any environment variables that will be needed by subprocesses
+          export JAVA_HOME
+          # dump env, but redact S3_KEY and S3_SECRET.
+          echo '****************************ENV******************************'
+          env | sed 's/S3_SECRET=.*$/REDACTED/' | sed 's/S3_KEY=.*$/REDACTED/'
+          echo '*************************************************************'
 
           # create expansions from values calculated above
           mkdir -p $ARTIFACTS_DIR
           cat <<EOT > $ARTIFACTS_DIR/expansions.yml
-          ARTIFACTS_DIR: "$ARTIFACTS_DIR"
-          SCRIPT_DIR: "$SCRIPT_DIR"
-          PLATFORM_NAME: "$PLATFORM_NAME"
           S3_ARTIFACTS_DIR: "$S3_ARTIFACTS_DIR"
           S3_RELEASES_DIR: "$S3_RELEASES_DIR"
-          PREPARE_SHELL: |
-             export PLATFORM="$PLATFORM"
+          MDBJDBC_VER: "$MDBJDBC_VER"
           EOT
 
     - command: expansions.update
       params:
-        file: artifacts/expansions.yml
+        file: adl-jdbc-driver/artifacts/expansions.yml
 
   "fetch jdbc files":
     - command: s3.get
       params:
+        working_dir: adl-jdbc-driver
         aws_key: ${aws_key}
         aws_secret: ${aws_secret}
-        remote_file: ${S3_ARTIFACTS_DIR}/mongo-jdbc-4.2.0.jar
-        local_file: build/libs/mongo-jdbc-4.2.0.jar
+        local_file: adl-jdbc-driver/build/libs/mongodb-jdbc-${MDBJDBC_VER}.jar
+        remote_file: ${S3_ARTIFACTS_DIR}/mongodb-jdbc-${MDBJDBC_VER}.jar
         bucket: mciuploads
 
   "fetch source":
@@ -88,26 +113,86 @@ functions:
       params:
         directory: adl-jdbc-driver
 
-  "upload test results":
+  "upload test classes":
     - command: s3.put
       params:
         aws_key: ${aws_key}
         aws_secret: ${aws_secret}
         local_files_include_filter:
-            - build/reports/tests/test/*
-        remote_file: ${S3_ARTIFACTS_DIR}/
-        content_type: text/plain
+            - adl-jdbc-driver/build/reports/tests/test/classes/*.html
+        remote_file: ${S3_ARTIFACTS_DIR}/classes/
+        content_type: text/html
+        bucket: mciuploads
+        permissions: public-read
+        display_name: "Test Classes"
+        visibility: none
+
+  "upload test packages":
+    - command: s3.put
+      params:
+        aws_key: ${aws_key}
+        aws_secret: ${aws_secret}
+        local_files_include_filter:
+            - adl-jdbc-driver/build/reports/tests/test/packages/*.html
+        remote_file: ${S3_ARTIFACTS_DIR}/packages/
+        content_type: text/html
+        bucket: mciuploads
+        permissions: public-read
+        display_name: "Test Packages"
+        visibility: none
+
+  "upload test index":
+    - command: s3.put
+      params:
+        aws_key: ${aws_key}
+        aws_secret: ${aws_secret}
+        local_file: adl-jdbc-driver/build/reports/tests/test/index.html
+        remote_file: ${S3_ARTIFACTS_DIR}/index.html
+        content_type: text/html
         bucket: mciuploads
         permissions: public-read
         display_name: "Test Results"
+
+  "upload test css":
+    - command: s3.put
+      params:
+        aws_key: ${aws_key}
+        aws_secret: ${aws_secret}
+        local_files_include_filter:
+            - adl-jdbc-driver/build/reports/tests/test/css/*.css
+        remote_file: ${S3_ARTIFACTS_DIR}/css/
+        content_type: text/css
+        bucket: mciuploads
+        permissions: public-read
+        display_name: "Test CSS"
+        visibility: none
+
+  "upload test js":
+    - command: s3.put
+      params:
+        aws_key: ${aws_key}
+        aws_secret: ${aws_secret}
+        local_files_include_filter:
+            - adl-jdbc-driver/build/reports/tests/test/js/*.js
+        remote_file: ${S3_ARTIFACTS_DIR}/js/
+        content_type: application/javascript
+        bucket: mciuploads
+        permissions: public-read
+        display_name: "Test JS"
+        visibility: none
+
+  "upload xunit test results":
+    - command: attach.xunit_results
+      params:
+        file: adl-jdbc-driver/build/test-results/*/TEST-*.xml
 
   "upload jar file":
     - command: s3.put
       params:
         aws_key: ${aws_key}
         aws_secret: ${aws_secret}
-        local_file: build/libs/mongo-jdbc-4.2.0.jar
-        remote_file: ${S3_ARTIFACTS_DIR}/mongo-jdbc-4.2.0.jar
+        local_file: adl-jdbc-driver/build/libs/mongodb-jdbc-${MDBJDBC_VER}.jar
+        remote_file: ${S3_ARTIFACTS_DIR}/mongodb-jdbc-${MDBJDBC_VER}.jar
         content_type: application/java-archive
         bucket: mciuploads
         permissions: public-read
