BI-2451: get rid of build_scripts

diff --git a/.evg.yml b/.evg.yml
--- a/.evg.yml
+++ b/.evg.yml
@@ -48,27 +48,43 @@ functions:
   "export variables":
     - command: shell.exec
       params:
-        working_dir: adl-jdbc-driver/build_scripts
+        working_dir: adl-jdbc-driver
         script: |
 
-          export PLATFORM='${_platform|unset}'
-          . "./prepare-shell.sh"
+          # set the state needed irrespective of _platform
+          ARTIFACTS_DIR=artifacts
+          S3_ARTIFACTS_DIR='adl-sql-driver/artifacts/${version_id}/${build_variant}'
+          S3_RELEASES_DIR='adl-sql-driver/releases/${version_id}/${build_variant}'
 
-          # our keys can currently only ulpad under the sqlproxy directory.
-          export S3_ARTIFACTS_DIR='adl-sql-driver/artifacts/${version_id}/${build_variant}'
-          export S3_RELEASES_DIR='adl-sql-driver/releases/${version_id}/${build_variant}'
+          # get the version from the gradle.properties file, so we don't need to update in two places.
+          MDBJDBC_VER="$(cat "gradle.properties" | head -n 1 | sed  s'/version\s*=\s*//')"
+
+          case '${_platform}' in
+          ubuntu1804-64-jdk-8)
+               JAVA_HOME=/opt/java/jdk8
+          ;;
+          ubuntu1804-64-jdk-11)
+               JAVA_HOME=/opt/java/jdk11
+          ;;
+          *)
+               echo "ERROR: invalid value for \${_platform}: '$_platform'"
+               echo "Allowed values: 'ubuntu1604-64-jdk-8', 'ubuntu1604-64-jdk-11'"
+               exit 1
+          ;;
+          esac
+
+          # export any environment variables that will be needed by subprocesses
+          export JAVA_HOME
+          echo '****************************ENV******************************'
+          env
+          echo '*************************************************************'
 
           # create expansions from values calculated above
           mkdir -p $ARTIFACTS_DIR
           cat <<EOT > $ARTIFACTS_DIR/expansions.yml
-          ARTIFACTS_DIR: "$ARTIFACTS_DIR"
-          SCRIPT_DIR: "$SCRIPT_DIR"
-          PLATFORM_NAME: "$PLATFORM_NAME"
           S3_ARTIFACTS_DIR: "$S3_ARTIFACTS_DIR"
           S3_RELEASES_DIR: "$S3_RELEASES_DIR"
           MDBJDBC_VER: "$MDBJDBC_VER"
-          PREPARE_SHELL: |
-             export PLATFORM="$PLATFORM"
           EOT
 
     - command: expansions.update
